name: SUSHI Publish NHSE

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 'current'
  
      - name: Install SUSHI
        run: npm install -g fsh-sushi
      
      - name: Install Publisher
        run: ./_updatePublisher.sh -y

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Ruby
        run: sudo apt install ruby ruby-all-dev -y

      - name: Install Jekyll
        run: sudo gem install jekyll jekyll-plantuml

      - name: Install Graphvix
        run: sudo apt install graphviz

      - name: Build IG
        run: ./_genonce.sh ${{ vars.VALIDATOR_OFFLINE }}

      - name: Download and unpack font-awesome
        run: wget https://fontawesome.com/v4/assets/font-awesome-4.7.0.zip; unzip font-awesome-4.7.0.zip -d output

      - name: Publish IG Artefact
        uses: actions/upload-artifact@v3
        with:
          name: IG Archive
          path: ./output/

      - name: Prepare files for GitHub Pages
        run: |
          cp -r output _site;
          chmod -c -R +rX "_site/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Publish IG to GitHub Pages
        uses: actions/upload-pages-artifact@v3

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}--build-cache-npm-packages-${{ hashFiles('**/package-lock.json') }}
